"""Produce readable report/captions from verified compact tables; no numerical worker."""
import csv,json,hashlib,datetime
from pathlib import Path
W=Path(__file__).resolve().parent
read=lambda n:list(csv.DictReader((W/'tables'/n).open()))
s=read('summary.csv');pairs=read('paired_changes.csv');ps=read('paired_summary.csv');ids=read('identity_counts.csv');agg=read('mean_vs_max.csv');tr=read('transition_checks.csv');ver=json.loads((W/'VERIFICATION.json').read_text())
def summ(pop,ds,T,k):return next(r for r in s if (r['population'],r['dataset'],int(r['T']),r['metric'])==(pop,ds,T,k))
def pair(pop,ds,seed,k,a=1,b=2):return next(r for r in pairs if (r['population'],r['dataset'],int(r['seed']),r['metric'],int(r['T_from']),int(r['T_to']))==(pop,ds,seed,k,a,b))
def fmt(r):return f"{float(r['mean']):.3f} +/- {float(r['sample_sd']):.3f}"
text=['# Group quality across zero, one and two refinement rounds\n',
'Completed 26 September 2026. **Saved-evidence first pass complete: 90/90 quality rows, 180 group rows, 30 dataset/seed/population cases, no exclusions, no new training or timing.** Two populations remain separate. `VERIFICATION.json` binds the exact inputs and analysis.\n',
'Worst-group cost decreased for every seed in both adjacent steps (60/60) and every T0-to-T2 comparison (30/30). Both individual group costs and population-average cost decreased from T0 to T2 in all 30 cases. However, T1-to-T2 increased Adult group 1 cost in **3/5 record-deletion seeds and 2/5 whole-client seeds**. Two of those record-deletion seeds also had higher population-average cost. Thus the observed decrease in Phi does not imply each group or the population average improves at every step.\n',
'## Scope and definitions\n',
'For a fixed seed s, retained represented population and T, Phi_g is the mean squared nearest-center distance in group g. All arithmetic begins with the saved exact integer fractions. Phi=max_g Phi_g; G=sum_g Phi_g; pooled SSE=sum_g n_g Phi_g; population-average cost=pooled SSE/sum_g n_g. G is neither Phi nor pooled SSE nor population-average cost. No training/timing repetitions are added as scientific seeds.\n',
'For each dataset/population/T, tables and bold plotted curves show (1/5) sum_s of the corresponding **case-level** metric, plus sample SD with divisor 4. In particular plotted worst-group mean=(1/5) sum_s max_g Phi_sg; this can exceed max_g[(1/5) sum_s Phi_sg]. Every case, exact rational mean and variance, range and group identity is in the CSVs. SD is descriptive variability, not a confidence interval. Counts are applied inside each seed before averaging; record-deletion group counts can vary across seeds.\n',
'Group meanings follow the frozen binary masks, not inferred membership: Adult group 0 is the complement of the stored male mask and group 1 is that male mask; Bank group 0 is not married and group 1 is married; Credit group 0 is other stored education codes and group 1 is EDUCATION in {1,2}. The intended Adult label for the complement is female, but we retain literal mask wording because Adult/Credit upstream raw files, fitted transforms and some semantic feature identities remain unverified. Source `src/datasets.py` and captured `context/stage1_protocol.tex` bind this interpretation. Preprocessing stays fixed, with b=12, clips 175/121/74, L=6, gamma=0, k=10 and no anchor Lloyd. T means **refinement rounds**; T0 still includes initialization.\n',
'## Separate populations and retained counts\n',
'A uses the CURRENT corrected record-deletion run `round-budget-20260926T064431Z`. The five original seeds 10000..10004 have their own preserved independent record requests: Adult/Credit delete 30, Bank deletes 45. All four saved gate methods have exactly equal indexed model witnesses and objective fractions at matched seed/T; quality is counted once using Fresh.\n',
'B uses completed `client-c0-20260926-v1` quality references for the same selected whole-client-deleted population as its core T0 experiment. Client 0 was prespecified by closeness to median client size with persistent-ID tie-breaking. All five seeds use this same request within a dataset. Saved fresh T1/T2 quality references are complete even though positive-T unlearning is outside this task. No result from the separate positive-refinement workspace was accessed.\n',
'| Population | Dataset | Original n | Deleted n | Retained group 0 | Retained group 1 | Retained total |\n|---|---|---:|---:|---:|---:|---:|']
for pop in ['record','client']:
 for ds in ['adult','bank','credit']:
  rr=[r for r in ids if r['population']==pop and r['dataset']==ds]
  def rng(k):
   vv=[int(r[k]) for r in rr];return str(min(vv)) if min(vv)==max(vv) else f'{min(vv)}-{max(vv)}'
  text.append(f"| {pop} | {ds.title()} | {rng('original_n')} | {rng('removed_n')} | {rng('n_group0')} | {rng('n_group1')} | {rng('retained_n')} |")
text+=['\nGroup count ranges summarize the five seeds; `identity_counts.csv` supplies every exact count and retained ordered-identity hash. Source-client/full-row IDs are preserved and survivors are never renumbered. Population identity consists of processed-source bytes, persistent ownership, original order and retained row identities. These are processed-array IDs, not newly validated native UCI IDs.\n']
for pop,label in [('record','A. Record-deletion quality'),('client','B. Whole-client-deletion quality')]:
 text += [f'## {label}\n','Absolute costs: mean +/- one sample SD over five seeds. Phi is the mean of within-seed maxima.\n','| Dataset | T | Group 0 | Group 1 | Worst group Phi | Population average |\n|---|---:|---:|---:|---:|---:|']
 for ds in ['adult','bank','credit']:
  for t in range(3):text.append(f'| {ds.title()} | {t} | '+' | '.join(fmt(summ(pop,ds,t,k)) for k in ['Phi_A','Phi_B','Phi','population_average'])+' |')
 text+=['\nPaired T0-to-T2 relative decreases: first compute (cost_0-cost_2)/cost_0 within each seed, then mean and range across five seeds. These differ from a ratio of dataset means and from T0 excess relative to T2, which uses a different denominator.\n','| Dataset | Group 0 mean [range] | Group 1 mean [range] | Phi mean [range] | Population mean [range] |\n|---|---:|---:|---:|---:|']
 for ds in ['adult','bank','credit']:
  cells=[]
  for k in ['Phi_A','Phi_B','Phi','population_average']:
   r=next(r for r in ps if (r['population'],r['dataset'],r['T_from'],r['T_to'],r['metric'])==(pop,ds,'0','2',k));cells.append(f"{100*float(r['relative_decrease_mean']):.2f}% [{100*float(r['relative_decrease_min']):.2f}, {100*float(r['relative_decrease_max']):.2f}]")
  text.append('| '+ds.title()+' | '+' | '.join(cells)+' |')
 text+=['\nAll three transitions (0->1, 1->2, 0->2) and all eight descriptive metrics have exact paired changes, mean, SD, min/max and decrease/increase/tie counts in `paired_changes.csv` and `paired_summary.csv`. Percentages are descriptive; no threshold was selected or tested.\n']
text+=['## Exceptions: improvements differ by group\n','Every event below is Adult T1->T2, with Phi decreasing. No such event occurs in Bank or Credit or for T0->T1/T0->T2. These are five distinct seed/population cases, not timing repeats; overlapping transitions are not counted as independent trials.\n','| Population | Seed | Group 1 before -> after | Group 1 change (%) | Phi before -> after | Population-average change |\n|---|---:|---:|---:|---:|---:|']
for ev in ver['group_increase_events']:
 pop=ev['population'];seed=ev['seed'];g=pair(pop,'adult',seed,'Phi_B');p=pair(pop,'adult',seed,'Phi');m=pair(pop,'adult',seed,'population_average')
 text.append(f"| {pop} | {seed} | {float(g['before']):.6f} -> {float(g['after']):.6f} | +{float(g['change']):.6f} (+{-100*float(g['relative_decrease']):.4f}%) | {float(p['before']):.6f} -> {float(p['after']):.6f} | {float(m['change']):+.6f} |")
text+=['\nThe guarded learner targets Phi; its stated monotonicity guarantee does not require a coordinatewise reduction of both group costs or population SSE. Reassignment alone weakly reduces group costs for fixed updated centers, but the preceding fair center update can trade one group\'s cost against another. This explanation invokes the existing guarded-update contract; the current task only verifies saved observations.\n',
'## Mean versus maximum, descriptive gaps and auxiliary objectives\n',
'Twelve of the 18 dataset/population/T rows have a strict difference between mean of seed maxima and maximum of group means. The complete check, with worst-group switching counts, is `mean_vs_max.csv`. For example:\n',
'| Population | Dataset | T | Mean of seed maxima | Max of group means | Difference |\n|---|---|---:|---:|---:|---:|']
for r in agg:
 if float(r['difference'])>0:text.append(f"| {r['population']} | {r['dataset'].title()} | {r['T']} | {float(r['mean_of_seed_maxima']):.6f} | {float(r['max_of_group_seed_means']):.6f} | {float(r['difference']):.6f} |")
text+=['\nAbsolute group gap=|Phi_0-Phi_1| and max/min group-cost ratio are included only as descriptive statistics. Ratio is undefined when the minimum group cost is zero; relative change is undefined when its initial denominator is zero. Undefined values use empty numerical fields plus status/count columns, not zero or infinity. There are no zero-denominator observations here; dedicated zero fixtures exercise this branch. These quantities are not new fairness definitions, guarantees of equalization or tests of downstream fairness.\n',
'Auxiliary G and pooled SSE below are on different scales and are deliberately absent from the per-record figure axes. Absolute five-seed mean +/- SD follows; exact means, variances and ranges are in `summary.csv`.\n',
'| Population | Dataset | T | G: sum of group means | Pooled SSE |\n|---|---|---:|---:|---:|']
for pop in ['record','client']:
 for ds in ['adult','bank','credit']:
  for t in range(3):text.append(f"| {pop} | {ds.title()} | {t} | {fmt(summ(pop,ds,t,'G'))} | {fmt(summ(pop,ds,t,'pooled_SSE'))} |")
text+=['\n## Figures and existing baseline evidence\n',
'`figures/record_group_quality.pdf` and `figures/client_group_quality.pdf` each show six panels. Upper row: individual group-average costs; lower row: within-seed worst-group and count-weighted population-average costs. Thin paths preserve all five seeds; bold markers and error bars show their mean and sample SD. Each dataset uses its own absolute cost axis with visibly nonzero origin, shared between its upper/lower panels. Seed IDs and exact values remain in the CSVs. The figures intentionally do not pool populations or overlay raw SSE.\n',
'Ghadiri, Samadi and Vempala, *Socially Fair k-Means Clustering*, Section 4/Figure 5 motivates showing both demographic-group costs. Figure 9 distinguishes population-average and worst-group objectives and reports variability. The supplied primary-paper extracted text is captured at `context/ghadiri2021socially.author_fulltext.txt` (PDF page markers 7-9); its numerical results, preprocessing choices, counts and convergence behavior are not targets or imported results. Section 3 already treats m groups; no multi-group novelty claim is made here.\n',
'**No valid ordinary-Lloyd versus fair-update comparator was found in the inspected P4/centralized evidence.** `context/stage1_protocol.tex`, paragraph P4 and baselines, says all initializers receive the same 15 guarded rounds on full cohorts without deletion. `context/corrected_p4_full_table.tex` identifies initialization-method/quantization comparisons at seed 42. `context/centralized.py` assigns each pooled point weight 1/n_g and samples weighted k-means++; it is a fair-weighted initializer. `context/p4_corrected.py` applies `guarded_fair_update` in the common refinement loop. Thus centralized does not mean ordinary k-means, and these full-population P4 rows are not matched to either survivor population here. Inspection scope is those evidence metadata and source files, not an exhaustive claim about every historical archive. No P4 runtime values were imported or rerun.\n',
'Optional future experiment only: freeze a matched same-survivor, same-seed and **identical initial-center** comparison of ordinary unweighted Lloyd mean updates versus guarded fair updates at equal T, with the same represented coordinates, assignments/ties and empty-cluster rules. Report both groups, Phi and count-weighted population cost for every case. Such a test would isolate update choice; an end-to-end ordinary initialization comparison is a separate question. This task stops at existing evidence and does not launch either experiment.\n',
'## Verification, concurrency and limitations\n',
'Executed checks: 702 frozen file SHA256/size/mtime comparisons; 51 source-copy checks for 17 canonical modules; original processed input/bundle hashes; complete source and row-identity registries; 15 record request mappings and 15 whole-client grid mappings; retained count conservation; 180 record gate model/exact-quality checks; 45 whole-client quality checks and 15 exact T0-core links; 60 cross-budget prefix checks; 90 scientific rows and 90 descriptive paired transitions; exact Phi/G identities and B saved SSE; saved-float consistency; 45 B CSV rows cross-checked; negative Phi, mean-vs-max, unequal-count and zero-denominator fixtures. A takes group counts from saved positive-T N statistics, checks original N against metadata and shares retained counts across exact prefixes. B cross-checks counts against frozen grid, saved core state and all quality witnesses. This is **saved-evidence verification and recombination, not independent raw-coordinate objective rescoring**. Raw arrays/checkpoints were not unpickled.\n',
'All substantial freeze/hash, analysis and render work ran as one worker under the parent-held exclusive flock at `/private/tmp/ftf_benchmark_20260926.lock`; lockfile preserved and released between batches. `LOCK_RECEIPTS.jsonl` records actual queue/acquire/release times, worker commands, exit codes, system load and top processes. Five numerical-library thread settings were fixed to one. No comparative timings were measured, so balanced timing order is not applicable; lock durations are operational receipts only. The lock does not control unrelated desktop load. Existing training environments were reused read-only.\n',
'| Claim status | What this task supports |\n|---|---|\n| Algebraically established | Phi/max, G/sum, count-weighted population mean/SSE, and the noncommutation of averaging and maximum follow their definitions; exact saved fractions satisfy them. |\n| Tested on completed evidence | All stated row counts, model links/prefixes, objective identities, paired decreases and exceptions, hashes and count conservation passed the documented checks. |\n| Conditional, inherited | The frozen map\'s guarded-Phi monotonicity and fixed-seed replay arguments require their stated arithmetic, fixed preprocessing, persistent identity, valid request and trusted-state assumptions. The whole-client review is source/snapshot-specific, not an independent endorsement of these quality summaries. |\n| Unresolved or untested | Ordinary-Lloyd advantage, optimum closeness, universal group improvement/equalization, an application quality threshold, personal-data erasure, identical full caches, model-adaptive fresh-independent distributional guarantees, cold/deployed runtime and new positive-T client-unlearning timings. |\n',
'## Deliverables and stop condition\n',
'`PROTOCOL.md`, `PROTOCOL_FREEZE.json`, `INPUT_MANIFEST.json`; `VERIFICATION.json`, `VISUAL_QA.json`, `FIGURE_RECEIPTS.json`, `LOCK_RECEIPTS.jsonl`, `FINAL_VERIFICATION.json`; all compact tables; `freeze.py`, `analyze.py`, `plot.py`, `with_lock.py`, `make_report.py`, `finalize.py`; `REPRODUCE.md`, `INTEGRATION_NOTES.md`, `MANIFEST.json`. One final PDF text-extraction check failed because its assumed executable path was absent; the installed bundled Poppler executable was then located and the final check repeated. That operational failure is preserved in FAILURE_RECEIPTS.json and the lock log. No scientific case, analysis outcome or figure was changed or selected by retry. Context snapshots preserve reading-time manuscript source and are not a restore source. The live manuscript, completed studies and frozen evidence were never written. No data download, archive duplication, iCloud export, external share, upload, submission or usage reset occurred. Outputs remain in the explicitly requested local workspace, outside iCloud; a separate backup choice is still needed. No disk-savings claim is made. The optional comparator remains unrun.\n']
(W/'REPORT.md').write_text('\n'.join(text))
notes='''# Integration notes and proposed captions

Proposals only; no live manuscript edit or Overleaf push. Source snapshots capture the reading-time context, not an authoritative replacement for human edits. Keep populations, five scientific seeds, and same-budget timing/equality scope separate. Do not insert new implementation details into main-paper prose.

## Main-text proposal

Across the three datasets, adding two refinement rounds reduced worst-group cost for all five seeds in each deletion study. The mean paired T0-to-T2 reductions were 19.76%, 31.17%, and 28.99% for record deletions, and 18.53%, 28.76%, and 35.26% for whole-client deletions (Adult, Bank, Credit). Improvements differed by group: during the second round, Adult's male-mask group cost rose in three record-deletion seeds and two whole-client seeds even as worst-group cost fell. In two record-deletion seeds, population-average cost also rose. These are observed quality changes within each study, not evidence of improvement over ordinary k-means or an application-level adequacy guarantee.

## Main-text caption proposals

**Figure A (record deletion).** Group quality across T=0,1,2 refinement rounds on retained records. Upper panels show each group-average squared cost; lower panels show worst-group and population-average costs. Thin lines are five paired seeds; bold markers are means and bars one sample SD. Worst-group costs are maximized within seed before averaging, and population costs are weighted by retained group counts within seed. All matched Fresh/replay methods have identical quality. Group definitions appear above panels; dataset axes differ. Adult group 1 rises in three seeds from T1 to T2 despite lower worst-group cost. No ordinary-Lloyd comparison is included.

**Figure B (whole-client deletion).** Matched fresh quality references at T=0,1,2 refinement rounds after removing one fixed client per dataset. Upper panels show group costs and lower panels worst-group and population-average costs. Thin lines preserve five seeds; bold markers and bars show means and one sample SD. Each seed's worst-group maximum and count-weighted population cost are computed before seed averaging. Group definitions appear above panels; dataset axes differ. Adult group 1 rises in two seeds from T1 to T2 despite lower worst-group cost. These populations are separate from record deletions, and T1/T2 quality references are not T0 unlearning timing denominators.

## Appendix caption / definitions proposal

For retained group g in seed s, let n_sg be its count and Phi_sg its average squared nearest-center distance on the fixed represented records. We report Phi_s=max_g Phi_sg, G_s=sum_g Phi_sg, pooled SSE_s=sum_g n_sg Phi_sg and population-average cost SSE_s/sum_g n_sg. Dataset-level curves average these case-level quantities over five seeds; variability uses sample SD with divisor four. Thus mean_s Phi_s need not equal max_g mean_s Phi_sg. Exact saved fractions determine all objectives and paired changes. T denotes refinement rounds after initialization. Timing repeats do not increase the number of scientific trials. Relative decreases use the earlier-budget cost as denominator; zero denominators are undefined. All cases and signed changes are retained in the supplementary CSVs.

Group 0/1 denotes complement/male mask (Adult), not-married/married (Bank), and other stored education codes/EDUCATION in {1,2} (Credit). This literal mask wording preserves the Adult/Credit raw-provenance limitation. The two studies have distinct survivors; no cross-population pooling is performed. T1/T2 whole-client results here are completed fresh quality references only. No erasure, full-cache equality, optimality, equalization or adaptive distributional conclusion follows from the saved model equalities.

## Suggested evidence placement

Use the two six-panel PDFs as appendix figures, or select one only if the main text can preserve both population identities and exceptions. Keep the numerical table of all five adverse group transitions nearby. Place exact definitions, counts, hash validation, source lineage, zero rules and P4 comparator inspection in the appendix/evidence report. The main text needs only the group-level observation and caveat.

Ghadiri Section4/Figures5,9 motivates the presentation of separate group costs and careful objective labels. Cite the existing manuscript key ghadiri2021socially for that conceptual connection, without importing its values or claiming equivalent preprocessing/baselines. Its Section3 already handles m groups. Existing P4 centralized initialization is globally fair-weighted and uses the same guarded refinement; it cannot support an ordinary-k-means improvement claim. A matched-start ordinary-Lloyd versus fair-update comparison is an optional future experiment, explicitly not executed here.
'''
(W/'INTEGRATION_NOTES.md').write_text(notes)
(W/'CORRECTNESS.md').write_text('''# Correctness and evidence scope

PASS. Read VERIFICATION.json for the executed machine-readable counts and exact source identities; REPORT.md details the tests and limitations. The analysis imports no training, replay, objective-evaluation or upstream aggregation functions. It uses Python integer Fraction arithmetic over saved group objectives and count witnesses, then derives all summaries and differences. Raw objective rescoring and independent numerical-kernel validation were deliberately outside this saved-evidence task.

All 45 record Fresh rows are backed by equal exact gate quality/model witnesses for four methods. All 45 whole-client quality rows have the frozen same-survivor counts and exact prefixes; each T0 witness equals its saved core Fresh output. Initial group-cost fields and arithmetic-derived objectives are checked exactly, including B's saved pooled SSE. A's derived SSE is new reporting arithmetic, not an originally saved scoring field. Original counts and identity maps are hash-bound; A counts derive from saved N, B counts agree across saved grid/core/quality.

The 90 rows are 30 dataset/seed/population cases times three budgets. There are five seeds per dataset/population, no timing-repeat pseudoreplication. Adjacent transitions total 60; the additional 30 endpoint comparisons overlap them. All 90 Phi changes are strictly negative. Adverse group changes occur only in Adult T1->T2 (3 record, 2 client); population cost increases occur in 2 record Adult T1->T2 cases. Every adverse case remains in tables and figures.

Fixtures reject an incorrect Phi and exercise unequal-count weighting, mean-versus-max aggregation and zero denominators. These directly test the reporting hazards addressed here; they do not re-prove the learner. SHA256 and mtime/size checks bind all 702 frozen files; 51 comparisons verify the three copies of 17 canonical source modules. Parent-held flock and thread-limit receipts document this task's substantial work, not historical benchmark execution. Visual QA checks both one-page PDF renders.
''')
print('Report, correctness record and integration proposals written.')
