"""Render compact Markdown from the saved verified experiment tables."""
from common import *
import csv,statistics,math
from datetime import datetime,timezone

def read(name):return list(csv.DictReader((ROOT/'tables'/name).open()))
def num(row,key):return float(row[key])
def mean(rows,key):return statistics.mean(num(r,key) for r in rows)
def table(headers,rows):return '| '+' | '.join(headers)+' |\n| '+' | '.join('---' for _ in headers)+' |\n'+'\n'.join('| '+' | '.join(str(v) for v in r)+' |' for r in rows)+'\n'
grid=json.loads((ROOT/'FROZEN_GRID.json').read_text())['cases'];raw=read('raw_timings.csv');case=read('case_method_timings.csv');ratios=read('paired_ratios.csv');aggregate=read('aggregate_timings.csv');prep=read('preparation_storage.csv');quality=read('quality.csv')
assert len(case)==45 and len(raw)==135 and len(quality)==45
by={(r['dataset'],r['method'],r['scope']):r for r in aggregate};cm={(r['case_id'],r['method']):r for r in case};q={(r['case_id'],int(r['T'])):r for r in quality}
fast=by['all','fast','request'];direct=by['all','direct','request'];fa=by['all','fast','algorithm'];da=by['all','direct','algorithm']
quality_ratios=[num(q[s['case_id'],0],'Phi')/num(q[s['case_id'],2],'Phi') for s in grid]
focus=json.loads((ROOT/'CORRECTNESS.json').read_text())
run=ROOT/'runs/client-c0-20260926-v1'
locks=[json.loads(line) for line in (run/'lock.jsonl').read_text().splitlines()]
acquired=[x for x in locks if x['event']=='acquired'];released=[x for x in locks if x['event']=='released']
assert len(acquired)==len(released)==30
allcore=sum(num(x,'request_e2e_seconds') for x in raw if x['method']=='fresh')
lines=['# Exact C0 whole-client deletion: bounded experimental result','',
f'Completed 26 September 2026. Run `client-c0-20260926-v1`. **The hypothesis is supported within this fixed whole-client, T=0, resident-data contract:** the compact-summary fast path matches canonical fresh T=0 exactly and is {num(fast,"ratio_of_total_times"):.2f}x faster by the ratio of total request times ({num(fa,"ratio_of_total_times"):.2f}x algorithm-only). All 15 prespecified case means exceed 10x. Existing canonical direct T=0 replay already reaches {num(direct,"ratio_of_total_times"):.2f}x request speedup; the new path is {num(direct,"method_total_seconds")/num(fast,"method_total_seconds"):.2f}x faster than direct in total request time. These figures describe this small simulation, not the established T=15 P2 learner or a deployed erasure service.','',
f'Quality is a material limitation: on these same populations, T=0 worst-group cost is {(min(quality_ratios)-1)*100:.1f}% to {(max(quality_ratios)-1)*100:.1f}% above fresh T=2. A correct deletion result reproduces the chosen learner; it does not remove the utility cost of choosing zero refinement. No quality acceptance threshold was specified, and no claim of T=0 adequacy follows.','',
'## What changed and why equality holds','',
'`client_c0.py` is a 95-line additive candidate; `implementation.diff` contains it. All 17 canonical source files remain byte-identical to the corrected September19 manifest. The fast state retains canonical per-slice summaries, original active client IDs, two integer counts per client, global counts and server settings. Counts are recovered from `n_e`, which local training already records. Initial compaction copies compact summaries and checks their multiplicities. It does not scan original records.','',
'For a whole-client request, all surviving ownership slices have the same represented records, original order and keyed local tape. Their cached summaries therefore equal fresh summaries. Removing the departing summaries and subtracting their counts produces fresh global n_g. Rebuilding the sorted (client,group,slot) anchor table creates the same exact h/n_g weights; calling the unchanged server sampler with the original server key creates the same indexed C0. The returned active state preserves this invariant for a valid whole-client sequence. Requests leaving either group empty are rejected. No server centers or weights are frozen.','',
'Fast deletion performs metadata/dictionary work, compact anchor materialization and canonical server sampling. It does not receive surviving raw coordinates, group arrays or row masks. Retaining O(C k d) summaries and O(C) counts avoids the existing direct path\'s once-per-request survivor scans and coordinate copies. Exact rational arithmetic still depends on count bit lengths; this is not a bit-complexity claim independent of population size.','',
'## Correctness actually checked','',
f'- {focus["tests_run"]} focused test methods passed, with {len(focus["exact_comparisons"])} saved exact fixture/sequence comparison records. Tests cover heterogeneous proportions, mixed/single-group departures, tiny/empty slices and empty clients, persistent ID gaps, unequal sizes, coincident coordinates/zero mass, saturation, quantized ties, optional anchor Lloyd, invalid requests, a one-per-group boundary and three sequential client removals.',
'- The fast API was exercised after replacing original raw/encoded/group dictionaries with access traps. Surviving summary objects are reused and their arrays are read-only; input state remains unchanged.',
'- All 15 dataset/seed cases completed all three method repetitions: 135 observations, 90 fresh-versus-replay model comparisons, and 90 comparisons of the explicitly claimed extra state. There were no exclusions, numerical mismatches, failed workers or selected reruns.',
'- Every indexed trajectory/final-center byte is compared, without tolerance or permutation. At T=0 the N/S/SS list is empty; this is not a new nonempty-statistics replay gate. Extra state compared: group counts, every surviving summary field including selected indices/reps/multiplicities, and the ordered anchor table with exact rational weights.',
'- `RESULTS_VERIFICATION.json` rechecks all 135 saved model files, their hashes, identical output witnesses, component time sums and balanced method positions. The 45 matched quality rows have the same retained counts and C0, and the expected trajectory/statistic lengths.',
'- Reference arithmetic is shared canonical FTF-1D code. This task\'s tests are not an independent rational oracle. Full fresh/raw caches are not required to equal the compact state, and model equality does not prove personal-data erasure.','',
'## Frozen cases and data','',
'The grid was frozen before new training or timing (`PROTOCOL.md`, `FROZEN_GRID.json`, SHA-256 `58f62126303df6e813ec76bd1bbab45d3e1c6383fd3bd9ce92ac4dd2be975615`). Canonical dataset-selection seed 0; training seeds 10000-10004; k=10, L=6, b=12, gamma=0, no anchor Lloyd. Fixed clips are 175/121/74. The valid client closest to original median size, tie-broken by its persistent run ID, is client 0 in each dataset. The choice does not vary with runtime, quality or seed. This is five seeds for the same selected whole-client request per dataset, not 15 distinct datasets or a variety of removal sizes.','']
lines.append(table(['Dataset','Original rows / clients / d','Removed rows (% total)','Removed group 0 / 1','Retained group 0 / 1'],[[s['dataset'].title(),f"{s['n']:,} / {s['C']} / {s['d']}",f"{s['removed_n']:,} ({100*s['removed_fraction']:.4f}%)",f"{s['removed_group_counts'][0]} / {s['removed_group_counts'][1]} ({100*s['removed_group_proportions'][0]:.2f}% / {100*s['removed_group_proportions'][1]:.2f}%)",f"{s['retained_group_counts'][0]:,} / {s['retained_group_counts'][1]:,}"] for s in grid[::5]]))
lines+=['Original run-client IDs and source-client/full-row identities are bound separately in `IDENTITY_REGISTRY.json`; survivors are never renumbered. Processed inputs are reused read-only and hash-matched to the accepted data manifest. Preprocessing is fixed, with the original Adult/Credit provenance limitations; nothing is refit or downloaded.','',
'## Timing contract and results','',
'All methods receive resident inputs; direct has its existing checkpoint and fast its previously prepared compact state. Fresh calls canonical `train_full(..., build_cache=False)` on survivor dictionary views. Direct calls canonical `unlearn(..., certificate_mode="none")` and pays for its existing masks/materialization. Fast takes client IDs only. Algorithm time encloses each public call. Request time adds request preparation and identical exact model-witness serialization/local write, without fsync. Initial data loading, process startup, checkpoint production, compaction, quality scoring and verification are outside request time and reported separately. No cold-fresh/warm-replay comparison, network latency, physical purge or updated-state persistence is claimed.','',
'Three repetitions rotate [fresh,direct,fast] by case index plus repetition; every method occupies every position once in each case. Reported totals use all observations. Paired case ratios divide mean fresh time by mean method time within a dataset/seed; repetitions are not treated as independent research cases.','']
summaryrows=[]
for ds in ('adult','bank','credit','all'):
 a=by[ds,'fast','algorithm'];d=by[ds,'direct','algorithm'];f=by[ds,'fast','request'];dr=by[ds,'direct','request']
 summaryrows.append([ds.title(),a['cases'],f"{num(d,'ratio_of_total_times'):.2f}x",f"{num(a,'ratio_of_total_times'):.2f}x",f"{num(dr,'ratio_of_total_times'):.2f}x",f"{num(f,'ratio_of_total_times'):.2f}x",f"{num(dr,'method_total_seconds')/num(f,'method_total_seconds'):.2f}x"])
lines.append(table(['Dataset','Cases','Fresh/direct alg.','Fresh/fast alg.','Fresh/direct request','Fresh/fast request','Direct/fast request'],summaryrows))
lines += [f'Across all 45 timed observations per method, fresh/direct/fast request totals are {num(fast,"fresh_total_seconds"):.6f} / {num(direct,"method_total_seconds"):.6f} / {num(fast,"method_total_seconds"):.6f} seconds. Algorithm totals are {num(fa,"fresh_total_seconds"):.6f} / {num(da,"method_total_seconds"):.6f} / {num(fa,"method_total_seconds"):.6f} seconds. The fast paired-case request ratio has mean {num(fast,"paired_case_ratio_mean"):.2f}, median {num(fast,"paired_case_ratio_median"):.2f}, sample SD {num(fast,"paired_case_ratio_sd"):.2f}, and range {num(fast,"paired_case_ratio_min"):.2f}-{num(fast,"paired_case_ratio_max"):.2f}. Its algorithm counterpart ranges {num(fa,"paired_case_ratio_min"):.2f}-{num(fa,"paired_case_ratio_max"):.2f}. Heterogeneous datasets explain much of the ratio variation; a pooled mean is not the ratio of total times.','',
'All case means follow. Absolute values are request milliseconds (three repetitions per method).','']
allrows=[]
for r in ratios:
 cid=r['case_id'];f=cm[cid,'fresh'];d=cm[cid,'direct'];v=cm[cid,'fast']
 allrows.append([r['dataset'].title(),r['seed'],f"{1000*num(f,'mean_request_e2e_seconds'):.3f}",f"{1000*num(d,'mean_request_e2e_seconds'):.3f}",f"{1000*num(v,'mean_request_e2e_seconds'):.3f}",f"{num(r,'fresh_over_fast_algorithm'):.2f}x",f"{num(r,'fresh_over_fast_request'):.2f}x",f"{num(r,'fresh_over_direct_request'):.2f}x"])
lines.append(table(['Dataset','Seed','Fresh ms','Direct ms','Fast ms','F/fast alg.','F/fast request','F/direct request'],allrows))
cv=[]
for method in ('fresh','direct','fast'):
 vals=[num(r,'sd_request_e2e_seconds')/num(r,'mean_request_e2e_seconds') for r in case if r['method']==method]
 cv.append(f'{method}: {100*min(vals):.2f}-{100*max(vals):.2f}%')
lines += ['Within-case request-time coefficients of variation across the three repeats: '+ '; '.join(cv)+'. Every standard deviation, min/max and observation is retained in `tables/case_method_timings.csv` and `tables/raw_timings.csv`. These are short, millisecond-scale operations on one workstation with only three repeats; no population-level confidence interval or universal 10x claim is made.','',
'## Measured component explanation and break-even','',
'Fresh pays for local seeding/assignment on all survivors; direct and fast reuse the unchanged summaries. Fast additionally removes direct\'s raw-data bookkeeping and copying. The compact server remains essentially the same cost in all three paths. Below are means over five seeds and three repetitions, in milliseconds; canonical direct\'s uninstrumented residual includes count scans/validation and timer/object overhead, so it is not labeled as pure scanning time.','']
comprows=[]
for ds in ('adult','bank','credit'):
 f=[r for r in case if r['dataset']==ds and r['method']=='fresh'];d=[r for r in case if r['dataset']==ds and r['method']=='direct'];v=[r for r in case if r['dataset']==ds and r['method']=='fast']
 comprows.append([ds.title(),f"{1000*mean(f,'mean_component_phase1_client_seconds'):.3f}",f"{1000*mean(f,'mean_component_encoding_seconds'):.3f}",f"{1000*mean(d,'mean_component_input_materialization_seconds'):.3f}",f"{1000*mean(d,'mean_component_phase1_client_seconds'):.3f}",f"{1000*mean(d,'mean_component_other_algorithm_seconds'):.3f}",f"{1000*mean(v,'mean_component_metadata_seconds'):.3f}",f"{1000*(mean(v,'mean_component_anchor_table_seconds')+mean(v,'mean_component_server_sampler_seconds')):.3f}"])
lines.append(table(['Dataset','Fresh local','Fresh encode','Direct materialize','Direct slice checks','Direct residual','Fast metadata','Fast table + server'],comprows))
lines += ['Writing the equal model output costs a further approximately 0.84/0.42/0.38 ms for fast Adult/Bank/Credit. The much smaller Bank anchor table (380 surviving slots versus 1,980 for Adult/Credit) explains its particularly small server cost and large fresh/fast ratio. It is a feature of this grid, not a favorable-case replacement rule.','',
'In a component model with common server/output cost S+O, write F=L+E+V+S+O for fresh local/encoding/other/server/output work and Q=M+S+O for fast metadata/server/output. A 10x speedup requires L+E+V >= 10M+9(S+O). Actual output times vary, so the saved observations define the reported ratios; adding refinement or durable purge/storage obligations changes this calculation. Current fast algorithm time is almost entirely rebuilding/sampling the compact server. There is no inference that raw-data Phase-II refinement could disappear at T>0.','',
'Incremental setup break-even is ceil(compaction / (fresh_request - fast_request)); versus direct, replace fresh by direct. It is one request in every measured case for both comparisons. If one charges the entire original training plus compaction to this new service before it serves any request, the analogous arithmetic is two independent requests in every case. This is a cost-accounting calculation using independent-request measurements; long sequential-service timing, erasure and state-persistence costs have not been measured.','',
'## Preparation and storage','']
prows=[]
for ds in ('adult','bank','credit'):
 r=[x for x in prep if x['dataset']==ds]
 prows.append([ds.title(),f"{1000*mean(r,'canonical_initial_training_seconds'):.3f}",f"{1000*mean(r,'incremental_compaction_seconds'):.3f}",f"{mean(r,'canonical_checkpoint_pickle_bytes')/1048576:.3f}",f"{mean(r,'compact_state_pickle_bytes')/1048576:.3f}",f"{1000*mean(r,'data_load_verify_seconds'):.3f}"])
lines.append(table(['Dataset','Original T0 train ms','Additional compaction ms','Canonical checkpoint MiB','Compact state MiB','Input load/verify ms'],prows))
lines += ['These are serialized object sizes measured with pickle protocol 5 in memory, not on-disk deletions or measured RAM savings. Full checkpoints were not saved anew. Compact state retains represented anchors/reps that can equal individual records, multiplicities, selected local indices and counts. Experimental source datasets, historical checkpoints and saved witnesses remain available; new full T=0 comparison checkpoints existed in their workers and were not persisted. `STATE_INVENTORY.md` and `tables/preparation_storage.csv` give the lifecycle/cost details. No actual disk savings are claimed.','',
'## Matched quality references','',
'One fresh T=1 and T=2 run per same client-deleted population, plus exact T=0 scoring, completed for all 15 cases. The table averages costs over five seeds; Phi is max(Phi_A,Phi_B) within each case, then averaged, so the average Phi need not equal the maximum of the two average group columns. Fractions and complete model/statistic witnesses are saved under `runs/.../quality`. These learning budgets are quality references, never denominators for T=0 unlearning ratios.','']
qrows=[]
for ds in ('adult','bank','credit'):
 for T in (0,1,2):
  r=[x for x in quality if x['dataset']==ds and int(x['T'])==T]
  qrows.append([ds.title(),T,f"{mean(r,'Phi_A'):.4f}",f"{mean(r,'Phi_B'):.4f}",f"{mean(r,'Phi'):.4f}",f"{mean(r,'pooled_SSE'):.2f}"])
lines.append(table(['Dataset','T','Mean group 0 cost','Mean group 1 cost','Mean worst-group cost','Mean pooled SSE'],qrows))
qr=[]
for ds in ('adult','bank','credit'):
 s=[x for x in grid if x['dataset']==ds];vals=[num(q[x['case_id'],0],'Phi')/num(q[x['case_id'],2],'Phi')-1 for x in s]
 qr.append(f'{ds.title()}: {100*min(vals):.1f}-{100*max(vals):.1f}%')
lines += ['Paired T=0 excess worst-group cost versus T=2: '+ '; '.join(qr)+'. No full-T=15 reference was run here and no Task A quality values were reused. `tables/quality.csv` reports every dataset/seed/budget and measured T=1/T=2 learning time separately.','',
'## Runtime, concurrency, attribution and limits','',
f'The host is an Apple M3 Max with 48 GiB RAM, macOS 27.0 arm64; Python 3.12.14 and NumPy 2.3.5 reused read-only. All five numerical thread environment controls were set to one, and one worker ran at a time. `threadpoolctl` is absent, so native pool sizes were not independently enumerated; `CURRENT_RUNTIME.json` records this limitation. All {len(acquired)} core/quality case batches acquired the required shared OS flock and released it after the worker finished. Total logged queue wait was {sum(x["wait_seconds"] for x in acquired):.3f}s; total held time was {sum(x["held_seconds"] for x in released):.3f}s. The separate correctness fixture also acquired the same lock.','',
'Batch load averages and top CPU processes are saved in `lock.jsonl`. macOS background processes were active, including uarpd at approximately one full core and variable WindowServer/Spotlight activity. The advisory lock coordinates the experimental tasks, not the entire workstation. No system, network or iCloud settings were altered.','',
'Pan et al. (ICLR 2023), primary supplied paper pp.6-8, motivates reusing unaffected local work and dropping whole-client contributions before server recomputation (Section 5.3/Algorithm 4). Lemma 5.1 concerns local seeding in distribution and Theorem 5.4 has conditional expected local complexity assumptions. Those guarantees are not substituted for this fair learner\'s same-seed proof. Primary PDF hash and exact source paths are in `REFERENCE_IDENTITIES.json`; relevant pages were text-extracted and visually checked. Locally balanced MERGED-1K is a separate adaptation and was not run. No new literature campaign or cross-paper speed-factor comparison was made.','',
'Limit the result to the unchanged fixed preprocessing/numerical map, trusted state, valid whole-client T=0 requests and specified output projection. There is no record-level prefix repair, arbitrary mutable-state validation, physical erasure, adaptive independent-distribution claim, broad quality acceptance, cold-start/deployed-latency estimate or replacement P2/P3 campaign. Saved original checkpoints, previous states and reports can retain personal information. Local files need a separately chosen backup; they are not claimed to be backed up by iCloud.','',
'## Independent-review handoff and deliverables','',
'`READY_FOR_REVIEW.json` points to immutable `review_snapshots/v1`, manifest SHA-256 `62bab6126a5708acc4d18902fe72bdae960b9d3e6582b0446cbafe7e97ea19c8`. It contains candidate, benchmark, canonical source, protocol and the focused test receipt. The snapshot has not been modified. Task C subsequently returned a scoped pass with no blocking finding for this exact hash: 196 independent valid-subset comparisons, 84 sequence steps and raw-access/timed-wrapper checks. Its source/functional and cost-boundary review does not independently certify the real-data timings, quality or aggregation here. `INDEPENDENT_REVIEW_STATUS.json` binds its separately authored `IMPLEMENTATION_REVIEW.md` and actual check record; no human review endorsement is implied.','',
'- `PROTOCOL.md`, `FROZEN_GRID.json`, `BASELINE_MANIFEST.json`, `INPUTS.json`, `ENVIRONMENT.json`: frozen design/provenance.',
'- `client_c0.py`, `implementation.diff`, `test_client_c0.py`, `CORRECTNESS.json`: candidate and actual focused test evidence.',
'- `tables/raw_timings.csv`, `tables/case_method_timings.csv`, `tables/paired_ratios.csv`, `tables/aggregate_timings.csv`, `tables/preparation_storage.csv`, `tables/quality.csv`: all observations and summaries.',
'- `runs/client-c0-20260926-v1`: individual identical-output model files, extra state witnesses, exact quality fractions, setup receipts and lock logs.',
'- `STATE_INVENTORY.md`, `REPRODUCE.md`, `INTEGRATION_NOTES.md`, `RESULTS_VERIFICATION.json`: costs, commands, scope and verification.',
'',
'All requested bounded experiments are complete. No baseline repository, live manuscript or Overleaf publication was changed, and no usage reset, external share, dataset download or bulky iCloud export was used.']
(ROOT/'REPORT.md').write_text('\n'.join(lines)+'\n')
print('REPORT.md written from all 135 observations and 45 quality rows.')
