import ReplayBundle
set_option pp.universes false

#check @Replay.patch_exact
#check @Replay.label_patch_exact
#check @Replay.abandonment_exact
#check @Replay.unchanged_correction
#check @Replay.changed_label_rejects
#check @Replay.summaries_equal
#check @Replay.initialized_state_equal
#check @Replay.canonical_active_congr
#check @Replay.whole_client_initializer
#check @Replay.summary_counts_exact
#check @Replay.whole_client_compact
#check @Replay.minimizers_nonempty
#check @Replay.nearest_le
#check @Replay.nearest_tie_smallest
#check @Replay.strict_winner_nearest
#check @Replay.nearest_square
#check @Replay.le_maxOn
#check @Replay.reverse_triangle_shift
#check @Replay.basic_certificate
#check @Replay.runner_certificate
#check @Replay.outward_bounds_sound
#check @Replay.basic_certified_label
#check @Replay.runner_certified_label
#check @Replay.integer_stats_patch
#check @Replay.integer_stats_abandonment
#check @Replay.owner_partition_sum
#check @Replay.local_multiplicity_conservation
#check @Replay.direct_stays_direct
#check @Replay.replayStep_equal
#check @Replay.trajectory_equal
#check @Replay.finite_trajectory_equal
#check @Replay.zero_round
#check @Replay.basicModel_sound
#check @Replay.basic_full_trajectory
#check @Replay.runnerModel_sound
#check @Replay.runner_full_trajectory
#check @Replay.Initializer.same_seed
#check @Replay.seeded_full_trajectory
#check @Replay.seeded_basic_exactness
#check @Replay.seeded_runner_exactness
#check @Replay.same_seed_event_law
#check @Replay.intervalGap_lower
#check @Replay.outward_runner_certificate
#check @Replay.outward_basic_certificate
#check @Replay.maxOn_le
#check @Replay.basic_implies_runner
#check @Replay.three_leave_one
#check @Replay.top_three_suffice
#check @Replay.overshoot_strict_improvement
#check @Replay.runner_only_counterexample
#check @Replay.radii_obstruction
#check @Replay.exact_norm_obstruction
#check @Replay.two_center_exact_obstruction
#check @Replay.maxOn_attained
#check @Replay.exists_third
#check @Replay.competitor_nonempty
#check @Replay.exact_norm_full_tightness
#check @Replay.radii_full_tightness
#check @Replay.stable_recurrence
#check @Replay.maxOn_bounded
#check @Replay.basic_failure_margin
#check @Replay.margin_failure_count
#check @Replay.stable_failure_scale
