"""Worker for the cross-process exactness test. Invoked via subprocess so
"fresh training" and "replay" genuinely run as separate top-level
processes -- appendix checklist item 9: "Replay must not call a coupled
oracle or reuse post-deletion labels generated by fresh training." Not a
pytest test module itself (leading underscore keeps it out of collection).
"""
import pickle
import sys

sys.path.insert(0, sys.argv[1])  # v1/src

from train import train_full  # noqa: E402
from unlearn import unlearn  # noqa: E402

mode, in_path, out_path = sys.argv[2], sys.argv[3], sys.argv[4]

with open(in_path, "rb") as f:
    payload = pickle.load(f)

if mode == "train":
    ckpt = train_full(payload["client_data"], payload["group_of"], payload["seed"],
                       payload["k"], payload["T"], payload["L"], gamma=payload["gamma"])
    with open(out_path, "wb") as f:
        pickle.dump({"digests": ckpt["digests"], "final_centers": ckpt["final_centers"], "checkpoint": ckpt}, f)
elif mode == "unlearn":
    with open(payload["checkpoint_path"], "rb") as f:
        ckpt = pickle.load(f)["checkpoint"]
    res = unlearn(ckpt, payload["removed"], certificate_mode=payload["certificate_mode"])
    with open(out_path, "wb") as f:
        pickle.dump({"digests": res["digests"], "final_centers": res["final_centers"]}, f)
else:
    raise ValueError(f"unknown mode {mode!r}")
