import FiniteRecords

#print axioms MatchedBudget.zero_ne_neg
#print axioms MatchedBudget.zero_ne_pos
#print axioms MatchedBudget.neg_ne_zero
#print axioms MatchedBudget.pos_ne_zero
#print axioms MatchedBudget.neg_ne_pos
#print axioms MatchedBudget.pos_ne_neg
#print axioms MatchedBudget.pair_law
#print axioms MatchedBudget.pair_nonneg
#print axioms MatchedBudget.pair_normalized
#print axioms MatchedBudget.no_repeated_location
#print axioms MatchedBudget.transfer_conservation
#print axioms MatchedBudget.endpoints_indexed_tie
#print axioms MatchedBudget.client_one_weights
#print axioms MatchedBudget.server_total
#print axioms MatchedBudget.merged_law
#print axioms MatchedBudget.split_server_total
#print axioms MatchedBudget.split_law
#print axioms MatchedBudget.endpoint_probabilities
#print axioms MatchedBudget.merged_normalized
#print axioms MatchedBudget.split_normalized
#print axioms MatchedBudget.merged_nonneg
#print axioms MatchedBudget.split_nonneg
#print axioms MatchedBudget.group_costs
#print axioms MatchedBudget.g_cost
#print axioms MatchedBudget.phi_cost
#print axioms MatchedBudget.optimum_at_zero
#print axioms MatchedBudget.expected_merged_g
#print axioms MatchedBudget.expected_split_g
#print axioms MatchedBudget.expected_merged_phi
#print axioms MatchedBudget.expected_split_phi
#print axioms MatchedBudget.epsilon_bounds
#print axioms MatchedBudget.matched_ratios
#print axioms MatchedBudget.real_group_costs
#print axioms MatchedBudget.real_g
#print axioms MatchedBudget.real_phi
#print axioms MatchedBudget.real_optimum_at_zero
#print axioms MatchedBudget.rational_real_agreement
#print axioms MatchedBudget.local_categorical_valid
#print axioms MatchedBudget.slot_weights_nonnegative
#print axioms MatchedBudget.unused_slot_probability
#print axioms MatchedBudget.expected_g_cast
#print axioms MatchedBudget.expected_phi_cast
#print axioms MatchedBudget.matched_real_ratios
#print axioms MatchedBudget.client_cardinalities
#print axioms MatchedBudget.group_cardinalities
#print axioms MatchedBudget.weighted_location_sum
#print axioms MatchedBudget.record_first_law
#print axioms MatchedBudget.record_second_law
#print axioms MatchedBudget.record_pair_law
#print axioms MatchedBudget.global_location_sum
#print axioms MatchedBudget.indexed_endpoint_counts
#print axioms MatchedBudget.normalized_count_transfer
#print axioms MatchedBudget.count_parameters
#print axioms MatchedBudget.rational_parameter_realizable
#print axioms MatchedBudget.record_group_costs
#print axioms MatchedBudget.record_means_zero
#print axioms MatchedBudget.every_fair_candidate_zero
#print axioms MatchedBudget.guarded_fair_candidate_zero
#print axioms MatchedBudget.split_record_first_law
#print axioms MatchedBudget.nonsaturated_budgets
#print axioms MatchedBudget.four_slots
#print axioms MatchedBudget.finite_matched_witness
#print axioms MatchedBudget.record_transfer_counts
#print axioms MatchedBudget.client_one_location
#print axioms MatchedBudget.ownership_parameter
#print axioms MatchedBudget.ownership_fractions
#print axioms MatchedBudget.record_slot_weights
#print axioms MatchedBudget.record_merged_law
#print axioms MatchedBudget.record_split_weights
#print axioms MatchedBudget.record_split_law
#print axioms MatchedBudget.record_objectives
#print axioms MatchedBudget.finite_record_ratios
